services:

  postgres:
    image: postgres:18
    container_name: hcpcs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hcpcs_db
      POSTGRES_USER: hcpcs_user
      POSTGRES_PASSWORD: hcpcs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  airflow:
    image: apache/airflow:3.3.2
    container_name: hcpcs-airflow
    restart: unless-stopped
    depends_on:
      - postgres

    extra_hosts:
      - "host.docker.internal:host-gateway"

    dns:
      - 168.63.129.16

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://hcpcs_user:hcpcs_password@host.docker.internal:5432/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

      DB_HOST: host.docker.internal
      DB_PORT: "5432"
      DB_NAME: hcpcs_db
      DB_USER: hcpcs_user
      DB_PASSWORD: hcpcs_password

      PYTHONPATH: /opt/airflow/project

      _PIP_ADDITIONAL_REQUIREMENTS: "requests beautifulsoup4 psycopg2-binary"

    ports:
      - "8080:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/project/data
      - ./src:/opt/airflow/project/src
      - ./database:/opt/airflow/project/database

    command: standalone

volumes:
  postgres_data:
